quick fix for SDK instructions
kubeflow/kfp-tekton pull request #358
Opened 2020-11-09 22:58 UTC by animeshsingh

Takes some excerpts from Christian's website PR. 

I will be revisiting after release to figure out the overlap with User guide.

2020-11-09 22:59 UTC, animeshsingh commented
/assign @Tomcli

2020-11-09 23:05 UTC, animeshsingh commented
/retest

2020-11-09 23:24 UTC, ckadner requested changes

2020-11-09 23:24 UTC, ckadner commented on sdk/README.md
> +## Kubeflow Pipelines with Tekton SDK Overview
You need to update the link in the table of contents above:

```Diff
<   - [Extensions to the Kubeflow Pipelines SDK](#extensions-to-the-kubeflow-pipelines-sdk)
---
>   - [Kubeflow Pipelines with Tekton SDK Overview](#kubeflow-pipelines-with-tekton-sdk-overview)
```

2020-11-09 23:33 UTC, ckadner commented on sdk/README.md
> +## Kubeflow Pipelines with Tekton SDK Overview
I would rename it to "SDK Packages" -- less wordy

2020-11-09 23:44 UTC, ckadner approved these changes
/lgtm

2020-11-09 23:46 UTC, ckadner commented
/approve

2020-11-09 23:46 UTC, merged

2020-11-12 15:10 UTC, Udiknedormin commented on sdk/README.md
> +run = client.run_pipeline(experiment.id, 'parallal-join-pipeline', 'pipeline.yaml')
*'parallel-join-pipeline'?