Fix(sdk): chain nested conditions to work on non-dependable condition tasks.
kubeflow/kfp-tekton pull request #732
Opened 2021-09-14 00:39 UTC by Tomcli

**Which issue is resolved by this Pull Request:** 
Resolves #729 

**Description of your changes:**
When a same custom task is being used in multiple layer of conditions, it cannot depend on itself to create the parent/child condition layer because it will create a cycle reference. Therefore, we force tasks to check when conditions for all their parent conditions.

**Environment tested:**

* Python Version (use `python --version`): 3.8
* Tekton Version (use `tkn version`): 0.27
* Kubernetes Version (use `kubectl version`): 1.19
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2021-09-14 00:45 UTC, Tomcli commented
cc @Udiknedormin

2021-09-14 16:30 UTC, Udiknedormin requested changes
It seems to me it doesn't work fine with interleaved conditions:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import TEKTON_CUSTOM_TASK_IMAGES


PrintOp = load_component_from_text("""
  name: print
  inputs:
  - name: msg
  outputs:
  - name: stdout
  implementation:
    container:
      image: alpine:3.6
      command:
      - concat:
        - "echo "
        - { inputValue: msg }
""")

CEL_EXPRS_IMAGE = "cel-exprs/image:latest"
TEKTON_CUSTOM_TASK_IMAGES = TEKTON_CUSTOM_TASK_IMAGES.append(CEL_EXPRS_IMAGE)

def CEL_Exprs(**conds):
  arguments = [
    "--apiVersion", "custom.tekton.dev/v1alpha1",
    "--kind", "CelExprs",
    "--name", "cel_exprs",
  ]
  file_outputs = dict()
  for cond_name, cond in conds.items():
    arguments.append(f"--{cond_name}")
    arguments.append(cond)
    file_outputs[cond_name] = f'/tmp/tekton/{cond_name}'

  op = dsl.ContainerOp(
    name="cel-exprs",
    image=CEL_EXPRS_IMAGE,
    command=["sh", "-c"],
    arguments=arguments,
    file_outputs=file_outputs,
  )
  op.add_pod_annotation("valid_container", "false")
  return op


@dsl.pipeline("nested-condition test")
def nested_condition_test(a: int, b: int, c: int, d: int):
  op_abc = CEL_Exprs(ab = f"{a} < {b}", bc = f"{b} < {c}")
  op_d = CEL_Exprs(c = "{c} > 0")
  with dsl.Condition(op_abc.outputs["ab"] == 'true'):
    with dsl.Condition(op_d.output == 'true'):
      with dsl.Condition(op_abc.outputs["bc"] == 'true'):
        print_op = PrintOp(f"{a} < {b} < {c}")


if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(nested_condition_test, __file__.replace('.py', '.yaml'))
```

produces:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nested-condition-test
  annotations:
    tekton.dev/output_artifacts: '{"print": [{"key": "artifacts/$PIPELINERUN/print/stdout.tgz",
      "name": "print-stdout", "path": "/tmp/outputs/stdout/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "a", "type": "Integer"},
      {"name": "b", "type": "Integer"}, {"name": "c", "type": "Integer"}, {"name":
      "d", "type": "Integer"}], "name": "nested-condition test"}'
spec:
  params:
  - name: a
    value: ''
  - name: b
    value: ''
  - name: c
    value: ''
  - name: d
    value: ''
  pipelineSpec:
    params:
    - name: a
    - name: b
    - name: c
    - name: d
    tasks:
    - name: cel-exprs
      params:
      - name: ab
        value: $(params.a) < $(params.b)
      - name: bc
        value: $(params.b) < $(params.c)
      taskRef:
        name: cel_exprs
        apiVersion: custom.tekton.dev/v1alpha1
        kind: CelExprs
    - name: cel-exprs-2
      params:
      - name: c
        value: $(params.c)
      taskRef:
        name: cel_exprs
        apiVersion: custom.tekton.dev/v1alpha1
        kind: CelExprs
    - name: print
      params:
      - name: a
        value: $(params.a)
      - name: b
        value: $(params.b)
      - name: c
        value: $(params.c)
      taskSpec:
        steps:
        - name: main
          command:
          - echo $(inputs.params.a) < $(inputs.params.b) < $(inputs.params.c)
          image: alpine:3.6
        - image: busybox
          name: copy-results
          script: |
            #!/bin/sh
            set -exo pipefail
            cp /tmp/outputs/stdout/data $(results.stdout.path);
        params:
        - name: a
        - name: b
        - name: c
        results:
        - name: stdout
          description: /tmp/outputs/stdout/data
        stepTemplate:
          volumeMounts:
          - name: stdout
            mountPath: /tmp/outputs/stdout
        volumes:
        - name: stdout
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
              {"command": [{"concat": ["echo ", {"inputValue": "msg"}]}], "image":
              "alpine:3.6"}}, "inputs": [{"name": "msg"}], "name": "print", "outputs":
              [{"name": "stdout"}]}'
            tekton.dev/template: ''
      when:
      - input: $(tasks.cel-exprs.results.bc)
        operator: in
        values:
        - "true"
      - input: $(tasks.cel-exprs-2.results.c)
        operator: in
        values:
        - "true"
      - input: $(tasks.cel-exprs.results.ab)
        operator: in
        values:
        - "true"
      timeout: 0s
  timeout: 0s
```
i.e. the dependency of `cel-exprs-2` on `cel-exprs` is lost.

It's a similar case to the one I provided as a control sample for how it works in nested conditions created from different ops:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import CEL_ConditionOp


PrintOp = load_component_from_text("""
  name: print
  inputs:
  - name: msg
  outputs:
  - name: stdout
  implementation:
    container:
      image: alpine:3.6
      command:
      - concat:
        - "echo "
        - { inputValue: msg }
""")

class CEL_Condition(dsl.Condition):
  def __init__(self, pred: str, name: str = None):
    super().__init__(CEL_ConditionOp(pred).output == 'true', name)

def CEL_ExprOp(expr: str):
  return CEL_ConditionOp(expr)


@dsl.pipeline("nested-condition test")
def nested_condition_test(a: int, b: int, c: int):
  with CEL_Condition(f"{a} < {b}"):
    with CEL_Condition(f"{b} < {c}"):
      print_op = PrintOp(f"{a} < {b} < {c}")


if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(nested_condition_test, __file__.replace('.py', '.yaml'))
```

used to produce, correctly:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nested-condition-test
  annotations:
    tekton.dev/output_artifacts: '{"print": [{"key": "artifacts/$PIPELINERUN/print/stdout.tgz",
      "name": "print-stdout", "path": "/tmp/outputs/stdout/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "a", "type": "Integer"},
      {"name": "b", "type": "Integer"}, {"name": "c", "type": "Integer"}], "name":
      "nested-condition test"}'
spec:
  params:
  - name: a
    value: ''
  - name: b
    value: ''
  - name: c
    value: ''
  pipelineSpec:
    params:
    - name: a
    - name: b
    - name: c
    tasks:
    - name: condition-cel
      params:
      - name: outcome
        value: $(params.a) < $(params.b)
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
    - name: condition-cel-2
      params:
      - name: outcome
        value: $(params.b) < $(params.c)
      taskRef:
        name: cel_condition
        apiVersion: cel.tekton.dev/v1alpha1
        kind: CEL
      when:
      - input: $(tasks.condition-cel.results.outcome)
        operator: in
        values:
        - "true"
    - name: print
      params:
      - name: a
        value: $(params.a)
      - name: b
        value: $(params.b)
      - name: c
        value: $(params.c)
      taskSpec:
        steps:
        - name: main
          command:
          - echo $(inputs.params.a) < $(inputs.params.b) < $(inputs.params.c)
          image: alpine:3.6
     [...]

2021-09-14 18:18 UTC, Tomcli commented
In case of the interleaved conditions (condi a <- condi b <- condi a), it's hard for the system to know what when conditions it should add and which condition should run after. Although I can create a new data structure to check all the parent's dependencies, we might be introducing new bugs with this new data structure. 

I can update my implementation to accomplish your examples first, then we can check whether it can create new bugs if we add new runAfter on some of these conditions.

2021-09-15 01:51 UTC, Tomcli commented
So after some digging in the DSL, the example where you use `CEL_Condition` has a dependency because the inner `CEL_Condition` (condition-cel-2) containerOp is created inside the first `CEL_Condition` block. Therefore the DSL labeled the inner `CEL_Condition` (condition-cel-2) as the child of (condition-cel). However, in the interleaved conditions example, both `CEL_Exprs` tasks are created outside of the condition block, so the DSL labeled them as the root nodes in the DAG. 

So I will try to do some extra checks to avoid unnecessary `when` condition if possible, but I will not add any runAfter logic since it breaks the DSL construct. If we want to create that dependency, we will be following the Argo DAG approach where we need a unique DAG (in tekton will be an extra unique task) to gate all the tasks inside the condition block.

2021-09-15 04:15 UTC, Tomcli commented
@Udiknedormin I removed the unnecessary `when` condition if possible now. If you want to add a when dependency to a custom task, you can do it as below. This way the DSL object can also have the dependency reference.

```
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import TEKTON_CUSTOM_TASK_IMAGES


PrintOp = load_component_from_text("""
  name: print
  inputs:
  - name: msg
  outputs:
  - name: stdout
  implementation:
    container:
      image: alpine:3.6
      command:
      - concat:
        - "echo "
        - { inputValue: msg }
""")

CEL_EXPRS_IMAGE = "cel-exprs/image:latest"
TEKTON_CUSTOM_TASK_IMAGES = TEKTON_CUSTOM_TASK_IMAGES.append(CEL_EXPRS_IMAGE)

def CEL_Exprs(**conds):
  arguments = [
    "--apiVersion", "custom.tekton.dev/v1alpha1",
    "--kind", "CelExprs",
    "--name", "cel_exprs",
  ]
  file_outputs = dict()
  for cond_name, cond in conds.items():
    arguments.append(f"--{cond_name}")
    arguments.append(cond)
    file_outputs[cond_name] = f'/tmp/tekton/{cond_name}'

  op = dsl.ContainerOp(
    name="cel-exprs",
    image=CEL_EXPRS_IMAGE,
    command=["sh", "-c"],
    arguments=arguments,
    file_outputs=file_outputs,
  )
  op.add_pod_annotation("valid_container", "false")
  return op


@dsl.pipeline("nested-condition test")
def nested_condition_test(a: int, b: int, c: int, d: int):
  op_abc = CEL_Exprs(ab = f"{a} < {b}", bc = f"{b} < {c}")
  with dsl.Condition(op_abc.outputs["ab"] == 'true'):
    op_d = CEL_Exprs(c = f"{c} > 0")
    with dsl.Condition(op_d.output == 'true'):
      with dsl.Condition(op_abc.outputs["bc"] == 'true'):
        print_op = PrintOp(f"{a} < {b} < {c}")


if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(nested_condition_test, __file__.replace('.py', '.yaml'))
```

Look at the function 
```
@dsl.pipeline("nested-condition test")
def nested_condition_test(a: int, b: int, c: int, d: int):
  op_abc = CEL_Exprs(ab = f"{a} < {b}", bc = f"{b} < {c}")
  with dsl.Condition(op_abc.outputs["ab"] == 'true'):
    op_d = CEL_Exprs(c = f"{c} > 0")
    with dsl.Condition(op_d.output == 'true'):
      with dsl.Condition(op_abc.outputs["bc"] == 'true'):
        print_op = PrintOp(f"{a} < {b} < {c}")
```

it should compiled to 
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nested-condition-test
  annotations:
    tekton.dev/output_artifacts: '{"print": [{"key": "artifacts/$PIPELINERUN/print/stdout.tgz",
      "name": "print-stdout", "path": "/tmp/outputs/stdout/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "a", "type": "Integer"},
      {"name": "b", "type": "Integer"}, {"name": "c", "type": "Integer"}, {"name":
      "d", "type": "Integer"}], "name": "nested-condition test"}'
spec:
  params:
  - name: a
    value: ''
  - name: b
    value: ''
  - name: c
    value: ''
  - name: d
    value: ''
  pipelineSpec:
    params:
    - name: a
    - name: b
    - name: c
    - name: d
    tasks:
    - name: cel-exprs
      params:
      - name: ab
        value: $(params.a) < $(params.b)
      - name: bc
        value: $(params.b) < $(params.c)
      taskRef:
        name: cel_exprs
        apiVersion: custom.tekton.dev/v1alpha1
        kind: CelExprs
    - name: cel-exprs-2
      params:
      - name: c
        value: $(params.c) > 0
      taskRef:
        name: cel_exprs
        apiVersion: custom.tekton.dev/v1alpha1
        kind: CelExprs
      when:
      - input: $(tasks.cel-exprs.results.ab)
        operator: in
        values:
        - "true"
    - name: print
      params:
      - name: a
        value: $(params.a)
      - name: b
        value: $(params.b)
      - name: c
        value: $(params.c)
      taskSpec:
        steps:
        - name: main
          command:
          - echo $(inputs.params.a) < $(inputs.params.b) < $(inputs.params.c)
          image: alpine:3.6
        - image: busybox
          name: copy-results
          script: |
            #!/bin/sh
            set -exo pipefail
            cp /tmp/outputs/stdout/data $(results.stdout.path);
        params:
        - name: a
        - name: b
        - name: c
        results:
        - name: stdout
          description: /tmp/outputs/stdout/data
        stepTemplate:
          volumeMounts:
          - name: stdout
            mountPath: /tmp/outputs/stdout
        volumes:
        - name: stdout
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
              {"command": [{"concat": ["echo ", {"inputValue": "msg"}]}], "image":
              "alpine:3.6"}}, "inputs": [{"name": "msg"}], "name": "print", "outputs":
              [{"name": "stdout"}]}'
            tekton.dev/template: ''
      when:
      - input: $(tasks.cel-exprs.results.bc)
        operator: in
        values:
        - "true"
      - input: $(tasks.cel-exprs-2.results.c)
        operator: in
        values:
        - "true"
      timeout: 0s
  timeout: 0s
```

print only needs to have when expression for the inner two condition since cel-exprs-2 is depended on cel-exprs's first condition.

2021-09-15 20:51 UTC, Udiknedormin commented
@Tomcli 
> So after some digging in the DSL, the example where you use `CEL_Condition` has a dependency because the inner `CEL_Condition` (condition-cel-2) containerOp is created inside the first `CEL_Condition` block. Therefore the DSL labeled the inner `CEL_Condition` (condition-cel-2) as the child of (condition-cel). However, in the interleaved conditions example, both `CEL_Exprs` tasks are created outside of the condition block, so the DSL labeled them as the root nodes in the DAG.

Checking:
```python
from kfp import dsl
from kfp.components import load_component_from_text
from kfp_tekton.tekton import TEKTON_CUSTOM_TASK_IMAGES


PrintOp = load_component_from_text("""
  name: print
  inputs:
  - name: msg
  outputs:
  - name: stdout
  implementation:
    container:
      image: alpine:3.6
      command:
      - concat:
        - "echo "
        - { inputValue: msg }
""")

CEL_EXPRS_IMAGE = "cel-exprs/image:latest"
TEKTON_CUSTOM_TASK_IMAGES = TEKTON_CUSTOM_TASK_IMAGES.append(CEL_EXPRS_IMAGE)

def CEL_Exprs(**conds):
  arguments = [
    "--apiVersion", "custom.tekton.dev/v1alpha1",
    "--kind", "CelExprs",
    "--name", "cel_exprs",
  ]
  file_outputs = dict()
  for cond_name, cond in conds.items():
    arguments.append(f"--{cond_name}")
    arguments.append(cond)
    file_outputs[cond_name] = f'/tmp/tekton/{cond_name}'

  op = dsl.ContainerOp(
    name="cel-exprs",
    image=CEL_EXPRS_IMAGE,
    command=["sh", "-c"],
    arguments=arguments,
    file_outputs=file_outputs,
  )
  op.add_pod_annotation("valid_container", "false")
  return op


@dsl.pipeline("nested-condition test")
def nested_condition_test(a: int, b: int, c: int, d: int):
  op_abc = CEL_Exprs(ab = f"{a} < {b}", bc = f"{b} < {c}")
  with dsl.Condition(op_abc.outputs["ab"] == 'true'):
    op_d = CEL_Exprs(c = "{c} > 0")
    with dsl.Condition(op_d.output == 'true'):
      with dsl.Condition(op_abc.outputs["bc"] == 'true'):
        print_op = PrintOp(f"{a} < {b} < {c}")


if __name__ == '__main__':
  from kfp_tekton.compiler import TektonCompiler as Compiler
  Compiler().compile(nested_condition_test, __file__.replace('.py', '.yaml'))
```
indeed does return:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nested-condition-test
  annotations:
    tekton.dev/output_artifacts: '{"print": [{"key": "artifacts/$PIPELINERUN/print/stdout.tgz",
      "name": "print-stdout", "path": "/tmp/outputs/stdout/data"}]}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"print": [["stdout", "$(results.stdout.path)"]]}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "a", "type": "Integer"},
      {"name": "b", "type": "Integer"}, {"name": "c", "type": "Integer"}, {"name":
      "d", "type": "Integer"}], "name": "nested-condition test"}'
spec:
  params:
  - name: a
    value: ''
  - name: b
    value: ''
  - name: c
    value: ''
  - name: d
    value: ''
  pipelineSpec:
    params:
    - name: a
    - name: b
    - name: c
    - name: d
    tasks:
    - name: cel-exprs
      params:
      - name: ab
        value: $(params.a) < $(params.b)
      - name: bc
        value: $(params.b) < $(params.c)
      taskRef:
        name: cel_exprs
        apiVersion: custom.tekton.dev/v1alpha1
        kind: CelExprs
    - name: cel-exprs-2
      params:
      - name: c
        value: $(params.c)
      taskRef:
        name: cel_exprs
        apiVersion: custom.tekton.dev/v1alpha1
        kind: CelExprs
      when:
      - input: $(tasks.cel-exprs.results.ab)
        operator: in
        values:
        - "true"
    - name: print
      params:
      - name: a
        value: $(params.a)
      - name: b
        value: $(params.b)
      - name: c
        value: $(params.c)
      taskSpec:
        steps:
        - name: main
          command:
          - echo $(inputs.params.a) < $(inputs.params.b) < $(inputs.params.c)
          image: alpine:3.6
        - image: busybox
          name: copy-results
          script: |
            #!/bin/sh
            set -exo pipefail
            cp /tmp/outputs/stdout/data $(results.stdout.path);
        params:
        - name: a
        - name: b
        - name: c
        results:
        - name: stdout
          description: /tmp/outputs/stdout/data
        stepTemplate:
          volumeMounts:
          - name: stdout
            mountPath: /tmp/outputs/stdout
        volumes:
        - name: stdout
          emptyDir: {}
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
              {"command": [{"concat": ["echo ", {"inputValue": "msg"}]}], "image":
              "alpine:3.6"}}, "inputs": [{"name": "msg"}], "name": "print", "outputs":
              [{"name": "stdout"}]}'
            tekton.dev/template: ''
      when:
      - input: $(tasks.cel-exprs.results.bc)
        operator: in
        values:
        - "true"
      - input: $(tasks.cel-exprs-2.results.c)
        operator: in
        values:
        - "true"
      - input: $(tasks.cel-exprs.results.ab)
        operator: in
        values:
        - "true"
      timeout: 0s
  timeout: 0s
```

Looks good to me then!

2021-09-15 20:51 UTC, Udiknedormin approved these changes

2021-09-15 21:51 UTC, Tomcli commented
@yhwang @ckadner can you lgtm this PR? thanks

2021-09-15 22:08 UTC, yhwang commented
/lgtm

2021-09-15 22:08 UTC, merged