Fix Tekton conditional dependency on sub-dag
kubeflow/kfp-tekton pull request #866
Opened 2022-03-01 02:48 UTC by Tomcli

**Which issue is resolved by this Pull Request:** 
Resolves #865 

**Description of your changes:**
Argo conditions are wrapped as sub-dag which cannot be dependent with its sub-dag tasks. However, this is not a correct representation for DSL which we have made Tekton to flatten out conditions into non-dag. Therefore, we need to update the dependency logic to depend on the flatten task instead of the removed sub-dag block. 

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

2022-03-01 02:48 UTC, Tomcli commented
cc @Udiknedormin

2022-03-01 14:37 UTC, Udiknedormin requested changes

2022-03-01 14:37 UTC, Udiknedormin commented on sdk/python/tests/compiler/testdata/loop_with_conditional_dependency.py
> +    op3.after(op1)
Please include both versions as unit tests.

To me it looks like B) works now but A) still doesn't work. Support for option A) is crucial in order to support empty loops (i.e. loops with no tasks inside).

2022-03-02 17:34 UTC, yhwang approved these changes
/lgtm

2022-03-02 17:35 UTC, merged